from django.db import models


class SportChoices(models.TextChoices):
    ATHLETICS = 'Athletics', 'Athletics'
    BADMINTON = 'Badminton', 'Badminton'
    BASKETBALL = 'Basketball', 'Basketball'
    BOXING = 'Boxing', 'Boxing'
    WRESTLING = 'Wrestling', 'Wrestling'
    GYMNASTICS = 'Gymnastics', 'Gymnastics'
    ROWING = 'Rowing', 'Rowing'
    JUDO = 'Judo', 'Judo'
    SWIMMING = 'Swimming', 'Swimming'
    PARAGLIDING = 'Paragliding', 'Paragliding'
    RUGBY = 'Rugby', 'Rugby'
    SHOOTING = 'Shooting', 'Shooting'
    SNOWBOARDING = 'Snowboarding', 'Snowboarding'
    SKIING = 'Skiing', 'Skiing'
    TABLE_TENNIS = 'Table Tennis', 'Table Tennis'
    TENNIS = 'Tennis', 'Tennis'
    TAEKWONDO = 'Taekwondo', 'Taekwondo'
    VOLLEYBALL = 'Volleyball', 'Volleyball'
    WEIGHTLIFTING = 'Weightlifting', 'Weightlifting'
    HANDBALL = 'Handball', 'Handball'
    HORSE_RIDING = 'Horse Riding', 'Horse Riding'
    ICE_HOCKEY = 'Ice Hockey', 'Ice Hockey'
    CHESS = 'Chess', 'Chess'
    CYCLING = 'Cycling', 'Cycling'
    FITNESS = 'Fitness', 'Fitness'
    FOOTBALL = 'Football', 'Football'
    FENCING = 'Fencing', 'Fencing'
    YOGA = 'Yoga', 'Yoga'
    KARATE = 'Karate', 'Karate'
    OTHER = 'Other', 'Other'


# class SportChoices(models.TextChoices):
#     ATHLETICS = 'Лека атлетика', 'Лека атлетика'
#     BADMINTON = 'Бадминтон', 'Бадминтон'
#     BASKETBALL = 'Баскетбол', 'Баскетбол'
#     BOXING = 'Бокс', 'Бокс'
#     WRESTLING = 'Борба', 'Борба'
#     GYMNASTICS = 'Гимнастика', 'Гимнастика'
#     ROWING = 'Гребане', 'Гребане'
#     JUDO = 'Джудо', 'Джудо'
#     SWIMMING = 'Плуване', 'Плуване'
#     PARAGLIDING = 'Парапланеризъм', 'Парапланеризъм'
#     RUGBY = 'Ръгби', 'Ръгби'
#     SHOOTING = 'Стрелба', 'Стрелба'
#     SNOWBOARDING = 'Сноуборд', 'Сноуборд'
#     SKIING = 'Ски', 'Ски'
#     TABLE_TENNIS = 'Тенис на маса', 'Тенис на маса'
#     TENNIS = 'Тенис', 'Тенис'
#     TAEKWONDO = 'Таекуондо', 'Таекуондо'
#     VOLLEYBALL = 'Волейбол', 'Волейбол'
#     WEIGHTLIFTING = 'Вдигане на тежести', 'Вдигане на тежести'
#     HANDBALL = 'Хандбал', 'Хандбал'
#     HORSE_RIDING = 'Езда', 'Езда'
#     ICE_HOCKEY = 'Хокей на лед', 'Хокей на лед'
#     CHESS = 'Шахмат', 'Шахмат'
#     CYCLING = 'Колоездене', 'Колоездене'
#     FITNESS = 'Фитнес', 'Фитнес'
#     FOOTBALL = 'Футбол', 'Футбол'
#     FENCING = 'Фехтовка', 'Фехтовка'
#     YOGA = 'Йога', 'Йога'
#     KARATE = 'Карате', 'Карате'
#     OTHER = 'Друго', 'Друго'