from django.db import models


class SportChoices(models.TextChoices):
    ATHLETICS = 'Лека атлетика', 'Лека атлетика'
    BADMINTON = 'Бадминтон', 'Бадминтон'
    BASKETBALL = 'Баскетбол', 'Баскетбол'
    BOXING = 'Бокс', 'Бокс'
    WRESTLING = 'Борба', 'Борба'
    GYMNASTICS = 'Гимнастика', 'Гимнастика'
    ROWING = 'Гребане', 'Гребане'
    JUDO = 'Джудо', 'Джудо'
    SWIMMING = 'Плуване', 'Плуване'
    PARAGLIDING = 'Парапланеризъм', 'Парапланеризъм'
    RUGBY = 'Ръгби', 'Ръгби'
    SHOOTING = 'Стрелба', 'Стрелба'
    SNOWBOARDING = 'Сноуборд', 'Сноуборд'
    SKIING = 'Ски', 'Ски'
    TABLE_TENNIS = 'Тенис на маса', 'Тенис на маса'
    TENNIS = 'Тенис', 'Тенис'
    TAEKWONDO = 'Таекуондо', 'Таекуондо'
    VOLLEYBALL = 'Волейбол', 'Волейбол'
    WEIGHTLIFTING = 'Вдигане на тежести', 'Вдигане на тежести'
    HANDBALL = 'Хандбал', 'Хандбал'
    HORSE_RIDING = 'Езда', 'Езда'
    ICE_HOCKEY = 'Хокей на лед', 'Хокей на лед'
    CHESS = 'Шахмат', 'Шахмат'
    CYCLING = 'Колоездене', 'Колоездене'
    FITNESS = 'Фитнес', 'Фитнес'
    FOOTBALL = 'Футбол', 'Футбол'
    FENCING = 'Фехтовка', 'Фехтовка'
    YOGA = 'Йога', 'Йога'
    KARATE = 'Карате', 'Карате'
    OTHER = 'Друго', 'Друго'
