# Generated by Django 4.2.16 on 2024-12-11 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('light', 'Light Package'), ('standard', 'Standard Package'), ('premium', 'Premium Package'), ('pro', 'Pro Package'), ('ultimate', 'Ultimate Package'), ('basic', 'Basic Package'), ('flex', 'Flex Package'), ('unlimited', 'Unlimited Package')], max_length=100)),
                ('description', models.TextField()),
                ('training_type', models.CharField(max_length=50)),
                ('session_count', models.IntegerField()),
                ('session_duration', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='accounts.trainerprofile')),
            ],
        ),
    ]
