# Generated by Django 4.2.16 on 2024-12-11 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('Athletics', 'Athletics'), ('Badminton', 'Badminton'), ('Basketball', 'Basketball'), ('Boxing', 'Boxing'), ('Wrestling', 'Wrestling'), ('Gymnastics', 'Gymnastics'), ('Rowing', 'Rowing'), ('Judo', 'Judo'), ('Swimming', 'Swimming'), ('Paragliding', 'Paragliding'), ('Rugby', 'Rugby'), ('Shooting', 'Shooting'), ('Snowboarding', 'Snowboarding'), ('Skiing', 'Skiing'), ('Table Tennis', 'Table Tennis'), ('Tennis', 'Tennis'), ('Taekwondo', 'Taekwondo'), ('Volleyball', 'Volleyball'), ('Weightlifting', 'Weightlifting'), ('Handball', 'Handball'), ('Horse Riding', 'Horse Riding'), ('Ice Hockey', 'Ice Hockey'), ('Chess', 'Chess'), ('Cycling', 'Cycling'), ('Fitness', 'Fitness'), ('Football', 'Football'), ('Fencing', 'Fencing'), ('Yoga', 'Yoga'), ('Karate', 'Karate'), ('Other', 'Other')], max_length=100)),
                ('certifications', models.TextField()),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('is_pending', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(default='Your coaching request is being processed.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
